language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: Build and release
      before_script:
        - npm run build
        - npm run sitemap
      after_success:
        - npm run release